### ISSUE TITLE
Interfaces with only IPv6 are skipped

### ISSUE THREAD

**Issue by wido** [sspans/ladvd#29] opened 2017-07-28 08:57 UTC
I'm testing with FreeNAS 11 (FreeBSD 11) and ladv and I was wondering why my switches weren't getting any neighbor information.

After running manually I found this:

<pre>
root@store01:~ # ladvd -o -L -f -vvv
child_init: ladvd 1.1.0 running
child_send: fetching all interfaces
netif_fetch: skipping interface ix0
netif_fetch: skipping interface ix1
netif_fetch: found ethernet interface igb0
netif_fetch: skipping interface igb0 (down)
netif_fetch: found ethernet interface igb1
netif_fetch: skipping interface igb1 (down)
netif_fetch: found ethernet interface igb2
netif_fetch: skipping interface igb2 (down)
netif_fetch: found ethernet interface igb3
netif_fetch: skipping interface igb3 (down)
netif_fetch: skipping interface lo0
netif_fetch: found bond interface lagg0
netif_fetch: adding interface lagg0
netif_fetch: detecting lagg0 settings
netif_fetch: fetching addresses for all interfaces
netif_iter: skipping interface lagg0
parent_signal: child exited with return code 0
parent_signal: quitting
root@store01:~ #
</pre>

I checked the source of *netif.c* and it only checks if there is a AF_INET address on a interface.

In my case *lagg0* only has a IPv6 address:

<pre>
root@store01:~ # ifconfig lagg0
lagg0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e407bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether ac:1f:6b:2c:31:76
	inet6 fe80::ae1f:6bff:fe2c:3176%lagg0 prefixlen 64 scopeid 0x8 
	inet6 2a05:1500:XX:YY:ae1f:6bff:fe2c:3176 prefixlen 64 autoconf 
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	groups: lagg 
	laggproto lacp lagghash l2,l3,l4
	laggport: ix0 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING>
	laggport: ix1 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING>
root@store01:~ #
</pre>

**Comment by sspans** [comment] 2017-07-29 09:44
Nice one! 

The code is supposed to be fully IPv6 capable so this must a small oversight somewhere.
I'll do a quick check to see if I can figure out what exactly is going wrong.

**Comment by wido** [comment] 2017-07-29 15:11
Thanks! Here is the full ifconfig output:

<pre>
ix0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e407bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether ac:1f:6b:2c:31:76
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect (10Gbase-Twinax <full-duplex,rxpause,txpause>)
	status: active
ix1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e407bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether ac:1f:6b:2c:31:76
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect (10Gbase-Twinax <full-duplex,rxpause,txpause>)
	status: active
igb0: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:db:e2:f4
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect
	status: no carrier
igb1: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:db:e2:f5
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect
	status: no carrier
igb2: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:db:e2:f6
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect
	status: no carrier
igb3: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 0c:c4:7a:db:e2:f7
	nd6 options=9<PERFORMNUD,IFDISABLED>
	media: Ethernet autoselect
	status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x7 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
lagg0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e407bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether ac:1f:6b:2c:31:76
	inet6 fe80::ae1f:6bff:fe2c:3176%lagg0 prefixlen 64 scopeid 0x8 
	inet6 2a05:1500:XX:XX:ae1f:6bff:fe2c:3176 prefixlen 64 autoconf 
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	groups: lagg 
	laggproto lacp lagghash l2,l3,l4
	laggport: ix0 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING>
	laggport: ix1 flags=1c<ACTIVE,COLLECTING,DISTRIBUTING>
</pre>

The message that shows it's skipping a interface is from this code:

<pre>
    for (ifaddr = ifaddrs; ifaddr != NULL; ifaddr = ifaddr->ifa_next) {

	// skip interfaces without addresses
	if (ifaddr->ifa_addr == NULL) {
	    my_log(INFO, "skipping interface %s", ifaddr->ifa_name);
	    continue;
	}
</pre>

That seems like it didn't detect an address. Are we use *ifaddrs* contains the IPv6 addresses of the interface?

**Comment by sspans** [comment] 2017-07-29 16:08
That part also detects ethernet addresses and ipv6 addrs, so the skipping is probably not from there.

```
./src/netif.c:	    my_log(INFO, "skipping interface %s", ifaddr->ifa_name);
./src/netif.c:	    my_log(INFO, "skipping interface %s", ifaddr->ifa_name);
./src/netif.c:	    my_log(INFO, "skipping interface %s", ifaddr->ifa_name);
./src/netif.c:	    my_log(INFO, "skipping interface %s", ifaddr->ifa_name);
./src/netif.c:	    my_log(INFO, "skipping interface %s (down)", ifaddr->ifa_name);
./src/util.c:	    my_log(INFO, "skipping interface %s", netif->name);
```

I suspect it's this one:
```
        } else if (type == NETIF_INVALID) {
            my_log(INFO, "skipping interface %s", ifaddr->ifa_name);
            continue;
        }
```

Which is based on a netif_type call. However it is pretty hard to guess at why that
function doesn't like your ix interfaces.

**Comment by sspans** [comment] 2017-07-31 06:19
I think the issue is the lagg driver, it changes the ix interfaces to IFT_IEEE8023ADLAG.

https://github.com/freebsd/freebsd/blob/master/sys/net/if_lagg.c#L708

**Comment by wido** [comment] 2017-07-31 09:07
Awesome! Hope that helps.

Testing this with FreeNAS is a bit difficult and I don't have a dev env right now. Will probably take some time before it gets into FreeNAS.

**Comment by sspans** [comment] 2017-08-05 12:09
Closing the issue as the issue seems to be resolved.

**Closed by sspans** 2017-08-05 12:09 UTC
