### ISSUE TITLE
LADVD stops working after bond creation

### ISSUE THREAD

**Issue by TomCos** [sspans/ladvd#36] opened 2018-09-08 20:08 UTC
The protocol breaks when a port-channel is created, which I'm assuming is not expected?  The threads below pretty much sum it up:

https://redmine.pfsense.org/issues/8139#change-36749
https://redmine.ixsystems.com/issues/27497

While I'm not sure if it's isolated to just FreeBSD 11, the bug is that LLDP completely breaks once a lag is activated.  I definitely have not looked at the code, but I would assume that even with a LAGG, we could just keep sending the LLDP frames down the physical interfaces.  From what it sounds like (from other threads, etc), the way FreeBSD handles the creation of the bond, those interfaces might disappear and that is no longer possible.  If that's the case, at the very least, can we move the frames to transmit on the bond then?  From the PFSense logs anyways, it looks like it's still trying to transmit on the physical interface.  The following log is directly from my box right now:

Sep 8 15:02:02	ladvd		interface ix1 is invalid
Sep 8 15:02:02	ladvd		interface ix0 is invalid
Sep 8 15:01:32	ladvd		interface ix1 is invalid
Sep 8 15:01:32	ladvd		interface ix0 is invalid
Sep 8 15:01:02	ladvd		interface ix1 is invalid
Sep 8 15:01:02	ladvd		interface ix0 is invalid
Sep 8 15:00:32	ladvd		interface ix1 is invalid
Sep 8 15:00:32	ladvd		interface ix0 is invalid
Sep 8 15:00:02	ladvd		interface ix1 is invalid
Sep 8 15:00:02	ladvd		interface ix0 is invalid

Maybe the underlying issue is it's still looking for the physical interfaces, when they no longer exist?

**Comment by sspans** [comment] 2018-09-08 21:03
The goal is to transmit on the individual bond members, but perform a fallback to the bond if that isn't possible. The lagg driver is kinda hard to deal with for ladvd due to the way it handles bond members.

Which exact FreeBSD version is triggering the problem?

**Comment by sspans** [comment] 2018-09-09 11:34
https://svnweb.freebsd.org/base/head/sys/net/if_lagg.c?revision=337709&view=markup#l991

Seems to indicate that outputting on the members should work for ethernet frames

**Comment by sspans** [comment] 2018-09-09 11:40
I've just noticed that you are testing with 1.1.1, so I suspect this is a duplicate of issue #29.

Can you please re-check with version 1.1.2?

**Comment by TomCos** [comment] 2018-09-09 23:42
My only implementation of LADVD is through PFSense, which manages their packages privately.  I updated the bug ticket there though to see if I get any traction.

**Comment by sspans** [comment] 2018-09-10 06:33
I guess the freebsd port needs to be updated.

**Comment by sspans** [comment] 2018-09-10 08:09
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231280

**Comment by sspans** [comment] 2018-09-10 08:09
Not sure how soon freenas/pfsense will pick this up

**Comment by woodsb02** [comment] 2018-09-10 12:56
I have just updated the FreeBSD port to v1.1.2.
https://www.freshports.org/net/ladvd

Note that this is in the "head" branch of the ports tree, so won't be available for 3 months for those following the quarterly branch.

**Closed** 2018-09-10 15:12 UTC
